name: Build OSX Distributable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Add Poetry to PATH
      run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

    - name: Install project dependencies
      run: poetry install

    - name: Install PyInstaller
      run: poetry add pyinstaller

    - name: Build with PyInstaller
      run: |
        poetry run pyinstaller --name pyevmlistener --onefile --console --distpath dist listener/main.py

    - name: Upload distributable
      uses: actions/upload-artifact@v4
      with:
        name: py-evmlistener
        path: dist/pyevmlistener
